using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Voidstation.KeycardActivator.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class KeycardActivatorMenu : FancyWindow
    {
        public event Action<string>? OnActionSelected;
        public event Action? OnBack;

        public KeycardActivatorMenu()
        {
            RobustXamlLoader.Load(this);

            RedCodeButton.OnPressed += _ => OnActionSelected?.Invoke("RedCode");
            CallERTButton.OnPressed += _ => OnActionSelected?.Invoke("CallERT");
            GetCodesButton.OnPressed += _ => OnActionSelected?.Invoke("GetCodes");

            BackButton.OnPressed += _ => OnBack?.Invoke();
        }

        public void ShowActivationScreen()
        {
            MainScreen.Visible = false;
            ActivationScreen.Visible = true;
        }

        public void ShowMainScreen()
        {
            MainScreen.Visible = true;
            ActivationScreen.Visible = false;
        }
    }
}
